// Auto-generated file - do not edit manually
// Generated by scripts/generate-graphics-data.ts

export interface GraphicsProject {
  id: string;
  title: string;
  client: string;
  type: string;
  dimensions: string;
  finish: string;
  description: string;
  tools: string[];
  images: Array<{
    src: string;
    width: number;
    height: number;
    alt: string;
    blurDataURL?: string;
  }>;
}

export const graphicsProjects: GraphicsProject[] = [
  {
    "id": "catalog-agr-carne-pui",
    "tools": [
      "Adobe InDesign",
      "Adobe Photoshop"
    ],
    "dimensions": "Various sizes",
    "client": "Agricola",
    "type": "Product Catalog",
    "finish": "Professional multi-page catalog with product photography",
    "title": "Agricola Chicken Meat Product Catalog",
    "description": "Comprehensive product catalog design showcasing Agricola's chicken meat product line. The catalog features professional food photography of various chicken meat products, with detailed product information, pricing, and promotional content. The design maintains Agricola's corporate branding while emphasizing product quality and freshness. Multiple spreads highlight different product categories including fresh chicken cuts, processed chicken products, and specialty items.",
    "images": [
      {
        "src": "/graphics-gallery/catalog-agr-carne-pui/catalog agricola carne de pui 1.png",
        "width": 3000,
        "height": 2250,
        "alt": "Agricola Chicken Meat Product Catalog - catalog agricola carne de pui 1",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAA4ElEQVR4nFXJ507CYACF4e82HThQ1ABKd6FgQVAsWBxBKstSsFCGXuNrKqGJP57kPTnC/nkj8f2KvXmhsnmmvO5QWrmYyzZ61EJY6w6JlYu1dClGT5hRG33hoM2bKOEDwohaGIsdB33uoIWPqGET+eseadbgZlpHxCMxizWQpnUKwR3XQY3cpErWtxH5oEZ+slMl71fJ+TbZz1uuxhUux2UyIwsRR2K0dTG0yAxLnA+KnA1MTvsGIj0w/0Ys3d+Kj5MPnWNP48hTSXkKIo5/eiqpnsJhT+bgXWa/K7HXLfALPCbLXHuSzccAAAAASUVORK5CYII="
      },
      {
        "src": "/graphics-gallery/catalog-agr-carne-pui/catalog agricola carne de pui 2.png",
        "width": 3000,
        "height": 2250,
        "alt": "Agricola Chicken Meat Product Catalog - catalog agricola carne de pui 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAA5ElEQVR4nF3QW1OCYBSFYX9jZ7MoJRFBQDwhYsTkdGWIRwRRO/zRt+HDqZnun1lr7V06nza5nrWozNs8rLrIsUMjHaFnz5jHgPbnhO73GyUBwxxaBdwMaCQu2m6McXjB+njF/pr8g8sOtXUfZTukmXromY9xCAQ+QZ1KZCGdYD12UJORSG3tfYxjUMCrUOc2Mrlf2FRXPVGfp6qph5aN0ff+HyxHBneL9m/9U+ygJK44TM08SmdTlctQ42ZmiJ3S0uZx3aO26SNvHerJECV1C3jxrokXleemSJVWHYGrcY4HyInDD6/KwKxfBmM9AAAAAElFTkSuQmCC"
      },
      {
        "src": "/graphics-gallery/catalog-agr-carne-pui/catalog agricola carne de pui 3.png",
        "width": 3000,
        "height": 2250,
        "alt": "Agricola Chicken Meat Product Catalog - catalog agricola carne de pui 3",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAAn0lEQVR4nF3KMQuCABAF4PtJRQ4NOjjUYFAtSZKRQg455NBWZmlSUpKRP/jF6Uni8MG7946m5QEzMWfflvK/kfEJYBR7TBrvloIF4B8a5T7GL7arPTt4y32QnnmoPNgW+r2D+8wDqakLpqUOtJsDlSUbqInklLmgYbxG5WrXLishmbvYBimRhdoSylmEQu5BZIH6oYnKaYFe49jCd2jiB0OzrDtoAg/ZAAAAAElFTkSuQmCC"
      }
    ]
  },
  {
    "id": "calendar-agricola-2025",
    "tools": [
      "CorelDRAW",
      "Adobe Photoshop"
    ],
    "dimensions": "210 x 120 mm",
    "client": "Agricola",
    "type": "Office Desk Calendar",
    "finish": "Professional corporate calendar with monthly layouts",
    "title": "Agricola Corporate Calendar 2025",
    "description": "Corporate desk calendar design for Agricola company for the year 2025. The calendar features modern corporate design with Agricola branding, showcasing various product lines throughout the months. The design incorporates professional food photography and clean typography suitable for office display. Multiple variations were created featuring different Agricola products and promotional content across the monthly pages.",
    "images": [
      {
        "src": "/graphics-gallery/calendar-agricola-2025/calendar agricola 2025 1.png",
        "width": 2200,
        "height": 1500,
        "alt": "Agricola Corporate Calendar 2025 - calendar agricola 2025 1",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAYAAAAxrNxjAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAx0lEQVR4nCWNS5aDIAAEvf9Wo0TUxORIERA/M0sFf+MJah5mUa83Xd3R6/yhPkbqvee5dTzXL/Xa89oH3sfI+/wlehwD1dZRLZbSt5TOUPn24hGkvaf+G4mKvUOuFukN0mnkrJCzRjpDubTfkWMgyjfLfTEIpxGzQkwNYlLcZ0XuDcVqKY6eSGwt2WJIZ0U6NaTT58osSF6Th7dQTLeW26JJnCKZm4tbwCmyRSPCYygmuyVeDbHXxE4Ru+bKxGvS1ZDtFnH2/ANSVes/nWR14QAAAABJRU5ErkJggg=="
      },
      {
        "src": "/graphics-gallery/calendar-agricola-2025/calendar agricola 2025 2.png",
        "width": 2200,
        "height": 1900,
        "alt": "Agricola Corporate Calendar 2025 - calendar agricola 2025 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAJCAYAAAALpr0TAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAwklEQVR4nFXPS5aDIBCFYfa/hPBSdxWBwu65PE2mN6fQ2KcH/4ivoBD6tUEfEaoTVAv/6wHqIKhXhGCkO0HzQfFQxd3J6iFbgOwE8UWaUXZQaT3LK2T+w8IwrAE6O2gGO/ccybRCFodH9Sc0NcBcUO/P0Q2vW4XtEbYG2Oxh0gqzMz7jFW449YipEabiYbODTQ7mSif+lIeqAWI+Nsw9Yq6MA6bsR+OF4s/9G0Es718sxw8Wxo3GwBiqBFsJpkWYvuED9MIzFeoeDG8AAAAASUVORK5CYII="
      },
      {
        "src": "/graphics-gallery/calendar-agricola-2025/calendar agricola 2025 3.png",
        "width": 2200,
        "height": 1500,
        "alt": "Agricola Corporate Calendar 2025 - calendar agricola 2025 3",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAYAAAAxrNxjAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAzUlEQVR4nD3MXXKCMABFYdZfQBERUWi7pYYk/GkfJQkRdAenI9Px4Zv7cuYGn48r1TxQ+p7z1L2VvqO693wtF76fvwSneaDwHUfXcLSao9HrFq7hNLWU957qcSXIfcfBNWRGsR8l2b+DUeSuWU/Oy0CQTg07q9iNkuQm2K1qUiPJrCL3LcUrTCbN1ko2Y83mJt4SU5NaReZb8qUniCdNZCXRKIjGH6KbIB4FG1OTOMX+3nJ4haHXhE4SmpoPIwiNILI1sZNsvSadW7LnwB+joOgrs4ha1AAAAABJRU5ErkJggg=="
      }
    ]
  },
  {
    "id": "promotie-agricola",
    "tools": [
      "Adobe Photoshop"
    ],
    "dimensions": "A3 (297 x 420 mm)",
    "client": "Agricola",
    "type": "Promotional Poster",
    "finish": "Professional promotional poster for discount campaign",
    "title": "Agricola Poultry Promotion Poster",
    "description": "Promotional poster design for Agricola's poultry discount campaign. The poster features discounted pricing and promotional messaging for chicken products, designed to attract customers with clear call-to-action elements. The layout emphasizes savings while maintaining Agricola's brand identity. The A3 size is ideal for in-store displays, window promotions, and countertop placement to drive sales during the promotional period.",
    "images": [
      {
        "src": "/graphics-gallery/promotie-agricola/Promo reducere pui fericit grill selgros sorin.png",
        "width": 4000,
        "height": 2667,
        "alt": "Agricola Poultry Promotion Poster - Promo reducere pui fericit grill selgros sorin",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAYAAAAxrNxjAAAACXBIWXMAAC4jAAAuIwF4pT92AAABB0lEQVR4nB3Ka0vCUBwH4PNZgigSpYtkIGJ5m1dmZ3Nztq3F0Tlxuhxa4ihUKoJeRB/4/P5Rz+uHff/s6fNrQ7u3mNYvAUUrl/yZRq7foJ5bpE7/khSeIfaX9h9LSrYhLTeCwnhAw2mX7KFCulugjpmlGk8T274vkOxCrJIRoicHQdSDN2nDEhVwJ4+2eYEaT4GtX8dYJuI/TWIDIlRh+3UYD9fo2ldomqeo8hOw6NlBuLIwXugQMxVu0EBflKDd59EZZFE3MqjwYzD/kUPMVXjTFuxAQX9YguYVoDo5NK0zKL0UyvwQzJko8i6oSmtUloYoSu7lperkZGtwLhUzLav6kby5PZC/aAiPz8n9SPYAAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "rollup-promo-agricola",
    "tools": [
      "Adobe Photoshop",
      "Adobe Illustrator"
    ],
    "dimensions": "850 x 2000 mm (portrait)",
    "client": "Agricola",
    "type": "Promotional Rollup Banner Series",
    "finish": "Professional rollup with stand",
    "title": "Agricola Promotional Rollup Collection",
    "description": "Collection of promotional rollup banner designs for Agricola's product lines. The series features multiple design variations showcasing different Agricola products and promotional campaigns. Each rollup maintains consistent brand identity while highlighting specific product offerings. The large vertical format ensures high visibility at trade shows, retail locations, and promotional events. Multiple design variations allow for flexible marketing across different product categories.",
    "images": [
      {
        "src": "/graphics-gallery/rollup-promo-agricola/Rollup AGR 1.png",
        "width": 3000,
        "height": 2500,
        "alt": "Agricola Promotional Rollup Collection - Rollup AGR 1",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAkklEQVR4nGWNWRaDIAxFWWkVSFBcRAsOdNmv5zHoRz8uZLhJjB4OyylYL0UsAdv3IRbFegnC6WCa6P/F0kT2wkFxtwgUT0G8FFshz7ZbFIqH7+ebTBhzmBKXGckzdHdYhtxhzBp7dIzPM+rWIXd4hTXJFj7NMC5NdUKzrdNs8tdMmuQ+EwwfJkIoZwtJgybZ9ws/3ZK3bg0JlGYAAAAASUVORK5CYII="
      },
      {
        "src": "/graphics-gallery/rollup-promo-agricola/Rollup AGR 2.png",
        "width": 3000,
        "height": 2500,
        "alt": "Agricola Promotional Rollup Collection - Rollup AGR 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAnklEQVR4nF2OWw6DIBREWXkLgu6hCKjb8IGv2m1NM6LW9GOSyZ2TA6JaNfykUEYJ2z/x6lLYeeNGRlzgcIBtiu2e+41bOEF3grS1jz0XON5AP2U38N+YnU+bBEYF28vbHyXKQR2ggajfOcKs4SKtCrajWaLsFVxUCJNOYLPlqBZafzDD7keNsBhQJppPgXql1eyDiynsfjao1hzNVuAL/mTkmrf8fR0AAAAASUVORK5CYII="
      },
      {
        "src": "/graphics-gallery/rollup-promo-agricola/Rollup AGR 3.png",
        "width": 3000,
        "height": 2500,
        "alt": "Agricola Promotional Rollup Collection - Rollup AGR 3",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAiElEQVR4nHWPXQ7DIAyDuRnhL7CDrBTodv83T8maStO2B0uJ+WQTR90jjYiyCvhgtEdVySxeGgnCONoJeSY16yFQU8lsYOgEF07Q0m7PpqqSuljfhPkLar2BH4mLv6oVtGrqpAv/+KN472NOUK+e5Uq1NPHiHkEbwfnN65JnvmCD8siIPcDfPV6fs5vAANSjjQAAAABJRU5ErkJggg=="
      },
      {
        "src": "/graphics-gallery/rollup-promo-agricola/Rollup AGR 4.png",
        "width": 1000,
        "height": 1400,
        "alt": "Agricola Promotional Rollup Collection - Rollup AGR 4",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAKCAYAAAB4zEQNAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAkElEQVR4nHXK2Q6CMBQE0PvfLiylQJFApYCIoFGpvznmUow86MPJTDJDxmrU7LViNRqrQcaWbvyBzFTio56PS580qHoW+If0I8eR3b/0gopbBketUqG4KtBhTJCPCThnQzzLhhiUXiKoPkLaC+cskLBOgGQXQHY+5MlHxFoPgjUeKGz3CJsdgppt4RvHqzZ4A6WPvSHjad2aAAAAAElFTkSuQmCC"
      }
    ]
  },
  {
    "id": "billboard-sibiu",
    "tools": [
      "Adobe Illustrator",
      "Adobe Photoshop"
    ],
    "dimensions": "1500 x 2000 mm",
    "client": "Agricola",
    "type": "Outdoor Billboard",
    "finish": "Large format print suitable for outdoor display",
    "title": "Agricola Salam de Sibiu - Awards Billboard",
    "description": "Promotional billboard design for Agricola's Salam de Sibiu product line, showcasing the brand's awards and achievements. The design emphasizes product quality and heritage through prominent display of awards (premii) and traditional branding elements. This billboard campaign highlights Agricola's commitment to quality and their recognized excellence in producing traditional Romanian salami.",
    "images": [
      {
        "src": "/graphics-gallery/billboard-sibiu/billboard salam de sibiu premii.png",
        "width": 4000,
        "height": 2667,
        "alt": "Agricola Salam de Sibiu - Awards Billboard - billboard salam de sibiu premii",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAYAAAAxrNxjAAAACXBIWXMAAC4jAAAuIwF4pT92AAAA+klEQVR4nC3KXUvCUBgH8POBgoIwyJCMYmFKkRHqdnTPXs/OzjanE80k7OWiC6/7uOf/BNHv+idy3WdTPrKZj7lofK42iue7muv9lpdfH7z6PvD68MMiUw7rfMC6GLKpJ1w0xOVGc7Vb/OfPvyySqItUOVB6gKwYQtcT5E0As85Qbueo3l5Qv+8hIrpAHHURJw7SrA9lhlDVGNnCh14lyDcFzGsDQdMWAmojDC8RxTeIVA+xfkBsnpGULtKakC4TiKl7gplswZ+dg6gDCq9AsQNK7kDqHqSfEOQjCHd0ZL3JsZXuqZXyzMpp20q/Y6XftR5dWy+4tV7Ys7+WypYzFbqKnAAAAABJRU5ErkJggg=="
      }
    ]
  },
  {
    "id": "poster-agricola-sibiu",
    "tools": [
      "Adobe Photoshop"
    ],
    "dimensions": "A2 (594 x 420 mm)",
    "client": "Agricola",
    "type": "Poster Design",
    "finish": "Professional print-ready poster",
    "title": "Agricola Salam de Sibiu - Awards Poster",
    "description": "A2 poster design promoting Agricola's Salam de Sibiu product line with awards/qualifications showcase. The poster highlights the product's recognized quality and accolades, using professional typography and visual hierarchy to draw attention to the awards. The design maintains Agricola's corporate branding while creating an impactful visual presence suitable for point-of-sale displays, trade shows, or promotional events.",
    "images": [
      {
        "src": "/graphics-gallery/poster-agricola-sibiu/agricola poster salam de sibiu premii.png",
        "width": 4000,
        "height": 3000,
        "alt": "Agricola Salam de Sibiu - Awards Poster - agricola poster salam de sibiu premii",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAA3UlEQVR4nCXM3ZJDMABAYe9/35221E8JESRICGq6+2Znp+nFufvmRPf7hTi+kCQ/ZNmN5zOhFjlKVWjdYq3Ge0v0eFxJ0ytpdqMoYsoypW4KVCfQRgW4fmBeJORFTPFMAhJ1jpQlXV9jRoV15gtLkVOJjErkiKagkWW4DVoyTj1uGfGbI2raik+yrWiVQPU1vZaYsWO2msXPbPtC1A0t3SBDvW4ZjMJMfUBunfC743h5IjNpzDyExnlgspp5GcPpg/bTc753IrvOfJtw68ziLevm2I6V49w43we/fyf/0mXw+CfDaB4AAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "flyer-sibiu",
    "tools": [
      "Adobe Photoshop"
    ],
    "dimensions": "A5 (210 x 148 mm)",
    "client": "Agricola",
    "type": "Promotional Flyer",
    "finish": "Professional promotional flyer",
    "title": "Agricola Salam de Sibiu - Promotional Flyer (German Version)",
    "description": "Promotional flyer design for Agricola's Salam de Sibiu product line, created in German language version for international marketing. The flyer showcases Agricola's traditional Romanian salami products with promotional content and product information tailored for German-speaking markets. The design emphasizes product quality and heritage while maintaining Agricola's corporate branding standards.",
    "images": [
      {
        "src": "/graphics-gallery/flyer-sibiu/flyer salam sibiu germania 1.png",
        "width": 3000,
        "height": 2250,
        "alt": "Agricola Salam de Sibiu - Promotional Flyer (German Version) - flyer salam sibiu germania 1",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAA50lEQVR4nFXQ206DQACEYR6b5UzF1ENMTFjoQpHaNDFewy4LtGpMfK/fWOpF77/MTMbZTitqm6CGiNKEFNpHag+pBdII5CCQo8Bp5ozapigTU+qQoveRnUfeu+TaJTcu0gqcdr6lsSsqk7DREUW3QNmJBf/D3XHNy5hRDylKx5R9cMEC2V/q/+D+457dOfWG2iQoHS649yi0R2EEhfVwDl+P7E93tNMyoTYxykRsTEBpfMrBpxx9nLfvJw6fD7ye1rRTRjOm5xcqG6JsyGYMUHOA8/7zzBU+ZjTziu2UUM8x1RxRHUN+Ade24F84Oer4AAAAAElFTkSuQmCC"
      },
      {
        "src": "/graphics-gallery/flyer-sibiu/flyer salam sibiu germania 2.png",
        "width": 3000,
        "height": 2250,
        "alt": "Agricola Salam de Sibiu - Promotional Flyer (German Version) - flyer salam sibiu germania 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAA+ElEQVR4nE3OW0+CAACGYX51q8xDHpABIhIgIiqnIFBMDBfOVuuXvU286f7Z971C8ZuQf4eklw1RvcQ/OawqC/do4JQz7HKKWWoI+U/0D83xjiaLwwx7r2EWKkahoBcyQvoVEJ+9ZqlB7zp2McHYyui5hJaNUTIR4fWyJvh0WX1YzZK1m2DkMtO3MWo6Qk4GjJM+Qnj2WJ8clscX5nsNY6s0SEmGSPEzYtxlEHcQ/NrFq+wm/NqkZxJqekOjqEM/fKIXthA29QK3srAPOsZOaZqud2LUvaHgkbZ/j7CqHRaViVVOmRUyaiYiJX2GUYde0KLtP9Dy7/gD66DgUGDU7aYAAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "raport-sustenabilitate-agr-2024",
    "tools": [
      "Adobe InDesign",
      "Adobe Illustrator",
      "Adobe Photoshop"
    ],
    "dimensions": "Various sizes",
    "client": "Agricola",
    "type": "Digital Publication Design (Sustainability Report)",
    "finish": "Professional multi-page digital publication",
    "title": "Agricola Sustainability Report 2024",
    "description": "Comprehensive sustainability report design for Agricola's 2024 environmental and social responsibility initiatives. The digital publication features a clean, modern layout with farming and crop imagery, using a green color scheme to reflect the environmental focus. The report includes sustainability metrics, corporate responsibility data, and visual storytelling to communicate Agricola's commitment to sustainable agricultural practices. Multiple page spreads organize information into clear sections with data visualizations and professional photography.",
    "images": [
      {
        "src": "/graphics-gallery/raport-sustenabilitate-agr-2024/Raport de sustenabilitate Agricola.png",
        "width": 3000,
        "height": 2250,
        "alt": "Agricola Sustainability Report 2024 - Raport de sustenabilitate Agricola",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAA5klEQVR4nBXK2XKCMABA0fy1M5aKAbKQkIUQEEWt0x+9nZ7nIz6/b14/B/fnnfWxUW4raa34ZWGcF0xeUKki3p8nx+vO7bhR98q8LcRa8GXG5oyOmSFkxH/aj411r5StkGpmKokxR0wMqGmi8x6xP1bWvVC2mVwToQRcnrDRo6aR3lnkaBB1myk1kpdAmD0uOWy06MnQO420ilb3iHkJpNkR8oiLFhs02it6NyBtR6slzdAiQrL4qBknhfEDyvX0ViLNlYtqaYZvzt0Xwvke4yR6lAz2SmdarvrCRX3T9A3n7sypPfEHZGjS86RogxMAAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "rollup-business-lounge-aeroport-enescu",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "850 x 2000 mm (portrait orientation)",
    "client": "Business Lounge, Henri Coandă International Airport (Aeroportul Henri Coandă)",
    "type": "Rollup Banner Display",
    "finish": "Professional rollup with stand, suitable for high-traffic airport environment",
    "title": "Airport Business Lounge Rollup - Henri Coandă International Airport",
    "description": "Elegant rollup banner design for the Business Lounge at Henri Coandă International Airport. The rollup features a portrait format with sophisticated typography and branding elements suitable for the premium airport lounge environment. The design communicates business-class services and amenities, using professional layout to create an upscale impression. The large vertical format (2000mm tall) ensures high visibility in the lounge area while taking minimal floor space. The rollup is designed for easy setup and transport, making it ideal for temporary promotions or permanent display in the lounge.",
    "images": [
      {
        "src": "/graphics-gallery/rollup-business-lounge-aeroport-enescu/rollup aeroport enescu business lounge 1.png",
        "width": 3000,
        "height": 2250,
        "alt": "Airport Business Lounge Rollup - Henri Coandă International Airport - rollup aeroport enescu business lounge 1",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA0ElEQVR4nF3K21KCQACA4X3/NxAnuIibmArBMQ/ULAdZT2hKCkYZzYTP8TelO2N915/Y10fWr5/MXiqibMdQrfHkAmeosHsxZkfSug0Q5UfD875mmleEl3E0we4lWJ7EuHtEFP/iIL2MYywvpH3/hCgODauyZrKpkAsdM5zRFPthjOVHtF2J2P2JBYN0gxfqmGL5sY5fLMsa9RMzHZc4wew3mn6M4YaI7Xtzivk5qvwc59h9hdlNMDoRYnvQ8Q2ZlacYrbgJ5lz3FVfdhJYb8Q27oAasO15DvQAAAABJRU5ErkJggg=="
      },
      {
        "src": "/graphics-gallery/rollup-business-lounge-aeroport-enescu/rollup aeroport enescu business lounge 2.png",
        "width": 3000,
        "height": 2250,
        "alt": "Airport Business Lounge Rollup - Henri Coandă International Airport - rollup aeroport enescu business lounge 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA20lEQVR4nEXM2U6DQABAUf7/3Vhc4ha3FIoJVoxlsQNSO9XBWqgWBSP1P64BJ/X95BjL+ofs7YvJvCSSOV6ScRVKLm9TTlzBvhPS648wimqNWtakLyvCac5NrHACycUGRpiWj5F/rnkuah6yFcE0ZxgrBi30Uo43MMBYfDQ8FRWJesd/XDAUioEvOe9gzJ5zj2mHGK9lwyyviDW8Fgrbl5x5KUca9lo4LxukhiMNrQ5OOHQTdp0x23bUwu8Oig7muCLD8mecarjzD/9GoVbcadjX8MBNMJ0xW3bEL4PyBGGHCxlRAAAAAElFTkSuQmCC"
      }
    ]
  },
  {
    "id": "leaflet-all-clean-and-clear",
    "tools": [
      "CorelDRAW",
      "Google AI Studio"
    ],
    "dimensions": "A4 (210 x 297 mm) folded in 3",
    "client": "All Clean and Clear",
    "type": "Tri-fold Leaflet",
    "finish": "Professional promotional leaflet",
    "title": "All Clean and Clear - Promotional Leaflet",
    "description": "Tri-fold promotional leaflet design for All Clean and Clear brand. The leaflet features a clean, modern layout showcasing cleaning products and brand information in a compact, portable format. The tri-fold design allows for organized content presentation with distinct sections for product information, benefits, and promotional messaging.",
    "images": [
      {
        "src": "/graphics-gallery/leaflet-all-clean-and-clear/pliant all clean and clear.png",
        "width": 3000,
        "height": 2250,
        "alt": "All Clean and Clear - Promotional Leaflet - pliant all clean and clear",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA1UlEQVR4nE2N6W6CUBSE7+s2RgEpa9JNL4hsfYC2imyy+I5fc6ht+mMymcw35yi/mAiLmbC8Eb7fCMuZoJjxshHneMWOOwzdoPx8WgoBfhUUE142/IGmgLIMcrk6EZY/HhTjHeyx4xZT1yg3HfCzgSAfF0Bcspv2PCYd26jB2F9QsnLTK172T2mPk3TLNUvXbHYVyj60y1IGzlG8w0la7EODFdUY+4r12xllRQ3buEEGUtqx5BpLX+7QidXLF0r+myJdY2pxyRWb3Zn164nV8ycPTx98A4GF0hU8VXnbAAAAAElFTkSuQmCC"
      },
      {
        "src": "/graphics-gallery/leaflet-all-clean-and-clear/pliant all clean and clear 2.png",
        "width": 3000,
        "height": 2250,
        "alt": "All Clean and Clear - Promotional Leaflet - pliant all clean and clear 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAn0lEQVR4nFWPSRKCMBBFc1kHwAjqzokIxDs4JYR4z299kiguuqqHV6+7RdUN2GiP7fX9jUp7lK2DvPTIa4Pl8QExBXcRZF12A2TToyB4ehJ0EfxZWVOwJqgMMoJc8bde+2Bso1FFI++YwskWbrThRoIrZcejOaAlhBvXcpafX1jwGSYJlk0AuJK99Mj8cIdgQpjNQtkA0FQbZNE229/wAWMXzHyskK5JAAAAAElFTkSuQmCC"
      }
    ]
  },
  {
    "id": "banner-biserica-narcisa",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "4500 x 1300 mm",
    "client": "Biserica Narcisa, Bacău",
    "type": "Outdoor Banner",
    "finish": "Reinforced with grommets/loopholes for mounting",
    "title": "Banner Biserica Narcisa - Sfântul Dumitru",
    "description": "Large format outdoor banner featuring Orthodox Christian iconography of Saint Dumitru (Saint Demetrius). The design incorporates traditional religious imagery with modern printing techniques suitable for outdoor church display. The banner is designed for durability and weather resistance.",
    "images": [
      {
        "src": "/graphics-gallery/banner-biserica-narcisa/Banner Biserica Narcisa Sfantul dumitru.png",
        "width": 4500,
        "height": 3000,
        "alt": "Banner Biserica Narcisa - Sfântul Dumitru - Banner Biserica Narcisa Sfantul dumitru",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAYAAAAxrNxjAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAvklEQVR4nD2M2VKDMAAA87keOJ1SKWdDUo5wJIUiVsefXSfI+LBvuytslWKrDFdnuKZgMhfuvWKxV9ap5Wvp+Xk4xKBjRp0wXhN85JqcyUjug+LD1Txmw/c6IjoZ0Zc7Kt4CV+/yqFlvzXYVbR7SFp4T5vJOV0Z/d3/uShZb8TkbRJUcqNOd7LhFXh78uSmYe7VdhY5e0VGAPgfo+A0fNnmIkV5OuRm5XYU8PiFDzzPy9IKKgn+5U2dsnTMPml/HkbBG2xYlRgAAAABJRU5ErkJggg=="
      }
    ]
  },
  {
    "id": "stradala-discover-imob",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "500 x 700 mm",
    "client": "Discover Imobiliare (Real Estate)",
    "type": "People Stopper / Pavement Sign",
    "finish": "Outdoor pavement signage for street-level marketing",
    "title": "Discover Imobiliare - People Stopper Design",
    "description": "People stopper (pavement sign) design for Discover Imobiliare real estate agency. The design serves as street-level advertising to attract potential clients walking by. The people stopper format is specifically designed for sidewalk placement, allowing businesses to capture attention from passing foot traffic. The compact dimensions (500x700mm) make it ideal for placement in front of real estate offices or property locations.",
    "images": [
      {
        "src": "/graphics-gallery/stradala-discover-imob/capra discover imobiliare.png",
        "width": 2500,
        "height": 1417,
        "alt": "Discover Imobiliare - People Stopper Design - capra discover imobiliare",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAGCAYAAAD68A/GAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAkElEQVR4nFXOVxKDMBRDUfa/uRQSMK4PA27UHSjjwWn/d45UKfEEqRaWOEYr4SeN6HvMacA6T9hXj2OPqCR/QMsGpBkGEpgGheAIKVgsacS2OBxbQCVYjayarJquqAYxZPUn7NobZFd/1V7AjRrBE+ZY5nPImis4u0PxohL/zP+F7eOCUz2/9u95Z5CiLaHHCwCv2mqdOMm7AAAAAElFTkSuQmCC"
      }
    ]
  },
  {
    "id": "banner-erasmus",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "4000 x 1000 mm",
    "client": "Erasmus+ E-Lev Program",
    "type": "Large Format Outdoor Banners",
    "finish": "Reinforced with grommets for mounting",
    "title": "Erasmus+ E-Lev E-Learning Program - Banner Collection",
    "description": "Collection of large format banners created for the Erasmus+ E-Lev E-Learning educational program. The project includes multiple banner variations showcasing different aspects of the program: 1. **E-Lev Program Banners (3 variations)** - Main program promotional banners featuring modern educational design with the European Union flag and Erasmus+ branding 2. **Health Awareness Banner** - \"Spune NU obezității!\" (Say NO to obesity!) health campaign banner focused on promoting healthy lifestyle choices The banners incorporate professional educational branding with modern design elements suitable for various promotional contexts within the educational program.",
    "images": [
      {
        "src": "/graphics-gallery/banner-erasmus/spune nu obezitatii.png",
        "width": 4000,
        "height": 2667,
        "alt": "Erasmus+ E-Lev E-Learning Program - Banner Collection - spune nu obezitatii",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAYAAAAxrNxjAAAACXBIWXMAAC4jAAAuIwF4pT92AAAA90lEQVR4nB3K21KCUBgGUF6pMppKyHLY6XjgoEiwBxBRwUDlXF0001Vvvb+/yXW9pO7jl+r6h4rTF2VpQbsooeDNJ8ewSGcjYopCaq9HUld9U3P+pDKrKN9nlIQxrR2PXN0gkzEaKX16vv2PxwZNVqJKc5ziPQ5+gM3KAdfnWDANE6WPoXwDqUsztMkB1XaH8zrCO/ewtZfw51PYbIiZ+gjtEuMYbbxBHYUoAo7MXWG3MBDOxnDYC3T1ASP5GlIXcrQhRxO4KLmD3LGQWDOsp69wtQFM5R7jS+RL0XJbNHwpStcSx5UuUnMioqkmPO1JWMqdmMhX4g8XmY51nfkxMgAAAABJRU5ErkJggg=="
      },
      {
        "src": "/graphics-gallery/banner-erasmus/Banner Erasmus 1.png",
        "width": 3000,
        "height": 2250,
        "alt": "Erasmus+ E-Lev E-Learning Program - Banner Collection - Banner Erasmus 1",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAABOUlEQVR4nCXK2UoCARQG4HmjLoKCiIo2tEURRbRlRB1Tx3HLJVPGNEUdDXUgJwytbMEKwyiIuurJzn+66Lv+hJlVkWc3vTy/FeBFq8wrjhhvuFNsFnO861fZFjpnu1JnYc7k54WdI162ybzujLN5P80Wb57twTN2KVU+SGrsybRZWLKGsGZXYHInYBGzsEsFuOUyPIkapOwFQgUdSsmAsOGMYXv/GDbvCVxBFWL0HIF0A5F8G4nSJbK1a+RbtxAshyk4fDnshVX44hWEsxoSagcnVQNqa4CKfo+6MYbglE5xIBchJStQck2kzroo1A1U2kNovUd0B6/ojaYQxEiRAskqRXNNypR1UrUrqus31Ok/kXE3oeH4gx7evkn4Txplyh0qNgxqdIek9x+pP5rQ6PmTXt5/aPr1S39buL7VsCnBSgAAAABJRU5ErkJggg=="
      },
      {
        "src": "/graphics-gallery/banner-erasmus/Banner Erasmus 2.png",
        "width": 3000,
        "height": 2250,
        "alt": "Erasmus+ E-Lev E-Learning Program - Banner Collection - Banner Erasmus 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAABOUlEQVR4nAXB7S8CARwH8PufvLCZGcNoNAqVSZccPShHD64OdT2duvLQ3abSKEu0jLHZjFf+sd/35/MRxuZFHrdJPGkP8bQzynPuY7Z5T9i+c8qrezlei5TYFauwMLEk8dRKmGfXY7y4GWe7qLBTOmN3OM9bss5iosYB5ZqFGUcECy4Zy94knIEMPKEstg9L2E1UEcxc4SBrQS60INg8R1jxpbAhqfBGcggclxFWapDPG0gWb5GudHB22YPgEFNw76nwRTXsx3XEMnUkNRPqRQva5QPK1hOM1hCCZ1+FP6ohmNAhq3UoBRO5ahv6TRf15gDm/Sua/Q8I/phGoYROslqndNGifK1NhtUjs/NC7cd36g6/aPD+Q0IwXiI5Y5BSaFDeaJFhdsm6e6ZO/436oy8aff7Sx/cf/QMQbME7vjHmNwAAAABJRU5ErkJggg=="
      },
      {
        "src": "/graphics-gallery/banner-erasmus/Banner Erasmus 3.png",
        "width": 3000,
        "height": 2250,
        "alt": "Erasmus+ E-Lev E-Learning Program - Banner Collection - Banner Erasmus 3",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAABOElEQVR4nAXB2UoCARQG4HmkLiKCigIztDATTRPN0gmdRs1lclzHXHItnQhTKEtSSsgWEALverLzn75PWDL4eHknwKu7QV63yrzluGCjW2GzL8sWscgHUoXtkQYLKyaR1ywh3rSFedsZZ7P3kvf9ObaHrtgVqbEn0eaTVJeFDasEgyMC01ECFp8K+1kebrkMX7wBUb2FlL9HpDSAYHRGsedJwnaahitYwHG0gjOlCTnXRbzUQ6r+iOzNCILFq8AeyMAtafDHqpDUFmKaDvW6j0J7iMrdGI3+FMKhmIHnXEMgVoWcbiFZ1JGr91HuPKPZm6D79IHe6w8Er6yRGK9SON0ipahTvtGn2t0LdQZv9DCa0fB9TuPPBQlirEJhtUmK1qVCvUc1fUj6YEKD0YxG0zlNvxf09ftH/0E9vlQObnPdAAAAAElFTkSuQmCC"
      },
      {
        "src": "/graphics-gallery/banner-erasmus/e-lev banner 4.png",
        "width": 4000,
        "height": 3000,
        "alt": "Erasmus+ E-Lev E-Learning Program - Banner Collection - e-lev banner 4",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAA90lEQVR4nCXD21KCQACA4X3RSondZQFr0MQDriCIQoc7OlxpdWM1zdDhAf8G+2Y+4dS/ONUP/eqb/vbruLdpOeuWLadly0nZItz6E7f6wN2+c77pvuGUh+P++kCvWxwQevuK3rygymdUuUeu98hih9vNdzir/8KUT5j1I17xgJffo/MGvWpQWYNMG9y04XzZIILiDj+/xc9uMOk1Jq3xbI22FWpRIZMaN6kRYZYTphmBTfEXS0xiMXOLnln01KImFhlbxMDGhMmYYD7Cnw4xkwgTR+hxhL6KUKMIOYwQg1lAOPUJYg9/rDEjhTdU6EiiLiXyQuEOFH80e8Nfb34ZnQAAAABJRU5ErkJggg=="
      }
    ]
  },
  {
    "id": "magazin-sibiu",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "1000 x 2400 mm",
    "client": "Jina Sibiului Shop",
    "type": "Shop Header / Signage",
    "finish": "Large format print for shop front display",
    "title": "Jina Sibiului Shop - Header Design",
    "description": "Large format shop header design for Jina Sibiului retail store. The design serves as the main storefront signage, featuring bold typography and visual elements to attract customers and establish brand identity. The vertical format is optimized for building-mounted display, creating a prominent street-level presence for the shop.",
    "images": [
      {
        "src": "/graphics-gallery/magazin-sibiu/magazin jina sibiului.png",
        "width": 2500,
        "height": 1786,
        "alt": "Jina Sibiului Shop - Header Design - magazin jina sibiului",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAYAAAAxrNxjAAAACXBIWXMAAC4jAAAuIwF4pT92AAAA7ElEQVR4nB3Ia0+CYACG4fd/W3MLChTlVEAcDFQIJSxABiXgIZH8Ve/T5MO9XbvJ9XJE1+5x+a3RniqcjxXaW6cK3bnBX3vAtTuBHOoSzS5H/Z2hKlPsiqTv5vonw77KcWxKkCKLsU3WyD5DJHGArw8fSewj3QT9y9MIxXYDEq8WiAIX4dLB+8JC4JkI5mbvle8gCl1s1kuQpWvCszXMTAWOIcPWxT7nVcabpWI+0+B7JoilSzBUAS8SB3X6CEVgoUzY3prMw3gWYOsSiDrlqDhiqPA0pCP2nvIPA8ozAzpm7+iEG1JpzFBV5Og/cYPL5BPJCNEAAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "billboard-kaufland",
    "tools": [
      "CorelDRAW",
      "Google AI Studio"
    ],
    "dimensions": "3000 x 1000 mm",
    "client": "Kaufland",
    "type": "Outdoor Billboard",
    "finish": "Large format print suitable for outdoor display",
    "title": "Kaufland Billboard Collection - Fresh & Bakery",
    "description": "Collection of billboard designs for Kaufland retail stores promoting various product categories: 1. **Fresh Vegetables Billboard** - Promotional billboard showcasing fresh produce with vibrant, high-quality food photography highlighting Kaufland's fresh vegetable offerings 2. **Bakery/Gogoşi Collection (2 variations)** - Billboard designs promoting Kaufland's bakery department, specifically featuring traditional Romanian pastries (gogoşi - Romanian donuts) with appetizing product photography The designs emphasize Kaufland's commitment to quality fresh foods and bakery products, using professional food photography to attract customers.",
    "images": [
      {
        "src": "/graphics-gallery/billboard-kaufland/billboard kaufland fresh.png",
        "width": 4000,
        "height": 3000,
        "alt": "Kaufland Billboard Collection - Fresh & Bakery - billboard kaufland fresh",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA7UlEQVR4nC3KyXaCQBQAUf5LgzSTU/OaQQQREQQROeT/l5VjksVdVVlvvWLSK156zajXPKMvhsj+IxsGcejFwZrF5i02L7EZ5RNtetnw+NeJQxs5WEvqMieKKVGMsWKIFb1RdEbRyodD8zvmAfMpYMp8xtRnSD0eiUdrXO7GpRFFrRXWUuyZzzumfMvzFNJnAV3ic499bsajjlwq7WJ9V5q5PDIVB57nPf1pR5uGNElAbQKu4nHRHtZSG+ZKeJWaoTjyyA/csx23ZMvVhFwkoNQ+1nJLeV9jxovQFxFdfqTJDtTJnsrsKCWkiEJ+APMWnTNoBohJAAAAAElFTkSuQmCC"
      },
      {
        "src": "/graphics-gallery/billboard-kaufland/billboard kaufland gogosi.png",
        "width": 4000,
        "height": 3000,
        "alt": "Kaufland Billboard Collection - Fresh & Bakery - billboard kaufland gogosi",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAABE0lEQVR4nBXDi06CYACA0f+tqikopYBoCl4yFDPwbiilNM1Iq+Wcl62trbXqYb/W2Y7ozNYMFlvGywOTl3fu3z6Ybz5ZbL+Idt9E+x+iwy+iOZrTvo3ohyv82SvBYs0k2jBdbglXO8LVnvD5gLBbPo1ugDuY0PFD+sGM4d0D/vQRfxrhh0/chEtE0W5SdTxqzQ5XXg+3PcTr+rR6I1r9Ma1+gNsLENlCGbNYpVSxuajWse0GtXqTunNNzXGxHZdLx0OkVAM9kyOXzZM/NzELRSyzRNEqY1llTKtC3qwgZFlBSZ6ROk2jpVR0VSejZchoBrpmoKkGadVAHB/FiJ3EkWISiXgCRUqiyP8VkrJCQlaQJIU/r1mo5vaORpkAAAAASUVORK5CYII="
      },
      {
        "src": "/graphics-gallery/billboard-kaufland/billboard kaufland gogosi 2.png",
        "width": 4000,
        "height": 3000,
        "alt": "Kaufland Billboard Collection - Fresh & Bakery - billboard kaufland gogosi 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA8klEQVR4nE3IW0+CcACG8f8Xy8khPEBkIJRLQZmZlgKlqRkO7aZ56F78sk9TWuvit/fdIyZfB2abA4tdxnJ/JP0+svpvn5HuM8Qo2RAvt4zTLdPVjvl6x/tnbr7OzVZbRC9eMHj9YDhOiN4S4umSl1/xNG/hJEF43SGd3ohuf8TjIKT/FDE4eY7O/9Qe+iHCbXg07n2arTae16HtB398P8DzApqtDsI0LW5qNrZVx7Udbusud07Orbs4tottOQjtskxFq6CXq5hVnWvdoKYb5zV1g6uqgV4xEIWLIlJBQi3KaJJCSVYoK+pZSVHRZBVVVvkBwRWujaInJTwAAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "rollup-lory-avon",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "850 x 2000 mm (portrait)",
    "client": "Lory Avon",
    "type": "Promotional Rollup Banner",
    "finish": "Professional rollup with stand",
    "title": "Lory Avon Promotional Rollup",
    "description": "Promotional rollup banner for Lory Avon featuring a portrait layout with the model and brand name prominently displayed. The rollup is designed for point-of-sale or event marketing, showcasing the Lory Avon brand with a clean, attractive visual presentation. The large vertical format (2000mm) ensures high visibility while maintaining a sleek, modern design suitable for beauty/cosmetic product promotion. The rollup is ideal for trade shows, retail environments, or promotional events where brand awareness and product appeal are key.",
    "images": [
      {
        "src": "/graphics-gallery/rollup-lory-avon/rollup lory avon.png",
        "width": 4000,
        "height": 3200,
        "alt": "Lory Avon Promotional Rollup - rollup lory avon",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAC4jAAAuIwF4pT92AAAAzUlEQVR4nC3G626DIACAUd59S7uqVe6IoELsnNlLfoudP05yxGeQ3L3i4RWNU7SXxiq+rORmJR9uQNyjphkNbTA8vaG/nG+95uE1N68QzWTpoqOPjmF0qFOwDMHSB0sXDI/RILo50KeATAE1BfSbf19GTz952uQQfYnIJaKXiJkjNv8zOaLyyJBHnvOIkFtG14ypGVsybj0l7Jowa0KtiaFOCLWv6O8V+1pw24K/nDfbgt5m5GtG6N+KOSr2qLifit9PBbcX7F7Qe0EdhT+tp9z5wGhUDgAAAABJRU5ErkJggg=="
      }
    ]
  },
  {
    "id": "salam-de-bacau",
    "tools": [
      "Adobe Illustrator",
      "Adobe Photoshop"
    ],
    "dimensions": "Various sizes",
    "client": "Salam de Bacău",
    "type": "Product Label Design & Mockups",
    "finish": "Professional product packaging design",
    "title": "Salam de Bacău - Product Label Design & Mockups",
    "description": "Product label design and mockup collection for Salam de Bacău (Bacău Salami) brand. The project features comprehensive label designs for traditional Romanian salami products, showcasing brand identity, product information, and quality certifications. The mockups demonstrate how the label designs appear on actual product packaging, providing realistic preview of final product presentation.",
    "images": [
      {
        "src": "/graphics-gallery/salam-de-bacau/Mockup Salam de bacau.png",
        "width": 3508,
        "height": 3000,
        "alt": "Salam de Bacău - Product Label Design & Mockups - Mockup Salam de bacau",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAJCAYAAAALpr0TAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAwklEQVR4nE3Q3bbDEBCGYZdcITgpgvRqEj+RXt/XNXTv1YP37DEGpuqGtWyQ2UFkh+W04KfFg8oWj+LAqwdThaCf8LQTHoSf4wDPDrx4ME0we8hzQnFYLMcTnBrQghc3oSoea3YTDzgnj2idMbEGjOu/U+fkuesfWuoGZlrELx4Hsh8PE8VDVI+lEbwSNOEW8P8DVJ2JFiCuCGb6DtMT9BWhGhWwfpNXgOwRoicw837B3Dv0naB7ghpFrKOE9U6Q7x0fHxXtSgaR5fgAAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "rollup-seby-sax",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "Various sizes",
    "client": "Seby Sax",
    "type": "Music Promotional Rollup",
    "finish": "Professional rollup display for music performances and events",
    "title": "Seby Sax - Music Promotional Rollup",
    "description": "Music promotional rollup design for Seby Sax, a musical performer/artist. The rollup features artist branding and performance imagery suitable for concerts, venues, and promotional appearances. The design captures the musical identity and creates a visually engaging presentation for audience engagement. Ideal for stage backdrops, venue entrances, or promotional events where artist visibility is essential.",
    "images": [
      {
        "src": "/graphics-gallery/rollup-seby-sax/rollup seby sax.png",
        "width": 2500,
        "height": 1875,
        "alt": "Seby Sax - Music Promotional Rollup - rollup seby sax",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAr0lEQVR4nG3OUY6DIABFUfa/iBaKCgiIqIDaxd1JGz8mpv835z0RvCfGSEqJnDPrulBKobXKse+c58H7fSKcc3g/EmMgpYmc5yveaLWy743zOBDGDDhr8eNIDIE0/Yp3RN93mOEW3+VWEVpr+u4Wx8icEkvObOtKLQWhlELrF1/5c8NZQvDfC/M8sywLZdsQUkpeStFpzTD02I/qR6abKp7PB0rKS+2xxlzz/7+u/AEDZPIoJiiX4AAAAABJRU5ErkJggg=="
      }
    ]
  },
  {
    "id": "mockup-snack2go",
    "tools": [
      "Adobe Illustrator",
      "Adobe Photoshop"
    ],
    "dimensions": "Various sizes",
    "client": "Agricola",
    "type": "Product Label Design & Mockups",
    "finish": "Professional product packaging design",
    "title": "Snack2Go Agricola - Product Label Design & Mockups",
    "description": "Product label design and mockup collection for Agricola's Snack2Go product line. The project features comprehensive packaging designs for convenient snack products, showcasing brand identity, nutritional information, and product imagery. The mockups demonstrate how the label designs appear on actual product packaging, providing a realistic preview of the final product presentation.",
    "images": [
      {
        "src": "/graphics-gallery/mockup-snack2go/Mockup Snack2go Produse.png",
        "width": 3508,
        "height": 3000,
        "alt": "Snack2Go Agricola - Product Label Design & Mockups - Mockup Snack2go Produse",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAJCAYAAAALpr0TAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAg0lEQVR4nJXPQQ7DIAxE0dwZm1wAcx6wud9EA0RFlbro4os4PBFy6ajIUZG94mZ9rZyZRoWMiosPOQy5G+4jzkzDIGGEBvUDtlVuBiX0DcU5FGgvyO2Tsl4gXpC8/AN5hw3n5pH8hCcmemEUXGn+1XrxXuEbTSjDMIsNd0T8Gg9Kw/AAyaLv0ylyJngAAAAASUVORK5CYII="
      }
    ]
  },
  {
    "id": "wedding-menu",
    "tools": [
      "CorelDRAW"
    ],
    "dimensions": "A4 (210 x 297 mm) bi-fold to A5 (210 x 148 mm)",
    "client": "Various clients",
    "type": "Wedding Menu Design",
    "finish": "Premium wedding stationery",
    "title": "Wedding Menu - Elegant Menu Design",
    "description": "Elegant bi-fold wedding menu design. A4 format folds to A5, creating a sophisticated presentation for wedding receptions. The menu features a refined layout suitable for formal dining occasions, with elegant typography and design elements that complement wedding aesthetics. The bi-fold format provides ample space for menu courses while maintaining an elegant, compact presentation for each guest setting.",
    "images": [
      {
        "src": "/graphics-gallery/wedding-menu/meniu nunta 1.png",
        "width": 3000,
        "height": 2250,
        "alt": "Wedding Menu - Elegant Menu Design - meniu nunta 1",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAt0lEQVR4nFXQWZKCQBBF0dr/MjocUXFoEBBBcdqKmVn2Gm5HMRj6f/LGi3QWFdiyxOIK29TY7oxPGvz+yiu78crv/BUPnM4LdFFiqyO2rrHtCf/b4NPLF3Y6y9HogC5LNK7Qvmqh+oGdTnOGqq6O6Lpqq+8JAadXnEwy5KsacDehxWFGcsHJeI9McmReINEB+cSbgE/43RknoxQZZ8i0x4u+3M4IuDtwz5+E5yhUuwlDecDt2+KafxnyCkKQtKAeAAAAAElFTkSuQmCC"
      },
      {
        "src": "/graphics-gallery/wedding-menu/meniu nunta 2.png",
        "width": 3000,
        "height": 2250,
        "alt": "Wedding Menu - Elegant Menu Design - meniu nunta 2",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAvklEQVR4nGXQXVbCMBBA4ex/HagIChT6Gy0tbcGtdDJhDdczLSjn8JC3LzeTcWHtCZ/fhO0RTVr0cEKznpgPxPLMtbpw9T+4sPKED4M1IWkIhxbNOjTvicVArGbsZOURg5uasGsI+xZN56oaLM/TcfJeIesv5Pb8XD2h6UO1GHCyLLlXZaoep+ofzjpi3uPkreSxKjarjZAYvn0u7XDyUjBj/483NWLlpEFt5n2LGxc542vBuKye8LQJu7Br+AXVDAuBW8W3qwAAAABJRU5ErkJggg=="
      },
      {
        "src": "/graphics-gallery/wedding-menu/meniu nunta 3.png",
        "width": 3000,
        "height": 2250,
        "alt": "Wedding Menu - Elegant Menu Design - meniu nunta 3",
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAu0lEQVR4nG3PWXKCQBhF4d7/OjIYMCgaRlHBIdlKT6zhpG5D5SkP/fbVuX+buf9h7r6J7ZPYPIj1nfA1EcqRsLvgtwM+7zFCs5BefSdWN8JxJJRXQnFeYCaYSkstVKrdCIcRv7/gBfMTTnCZexDSpGoTvrziNfs54LIT7qPDxGqdS2jErzVXnHFboR67aTHp8OO0zKkktFtRJtRh3xqMgH74h1TSZN6nSfveYl9rTDpa96hSDP+gBvtS8QsZogtv8cJGpgAAAABJRU5ErkJggg=="
      }
    ]
  }
];
